---
version: 2
jobs:
  build: &build
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install -e .
  test: &test
    docker:
      - image: circleci/python:3.7.2
      - image: influxdb:latest
      - image: redis:latest
    steps:
      - checkout
      - run:
          name: Install test extras
          command: sudo pip install -e .[test]
      - run:
          name: Run test
          command: make test
      - run:
          name: Install extras
          command: sudo pip install -e .[pandas,cache]
      - run:
          name: Run test again (w/ Pandas+Redis support)
          command: make test
      - run:
          name: See coverage report
          command: cat .coverage
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)
  build-3.6:
    <<: *build
    docker:
      - image: circleci/python:3.6.8
  test-3.6:
    <<: *test
    docker:
      - image: circleci/python:3.6.8
      - image: influxdb:latest
      - image: redis:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_and_test-3.6:
    jobs:
      - build-3.6
      - test-3.6:
          requires:
            - build-3.6
