version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install -e .
  test:
    docker:
      - image: circleci/python:3.6.4
      - image: influxdb:latest
    steps:
      - checkout
      - run:
          name: Install test extras
          command: sudo pip install -e .[test]
      - run:
          name: Run test
          command: make test
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
